import{d as p,r as d,b as h,k as l,w as n,aq as e,e as a,o as r,l as s}from"./style_icon.js";const o={class:"markdown-body"},m=e(`<h1>Empty</h1><h3>Intro</h3><p>Occupation reminder when empty.</p><h3>Install</h3><pre><code class="language-js"><span class="hljs-keyword">import</span> { createApp } <span class="hljs-keyword">from</span> <span class="hljs-string">&#39;vue&#39;</span>;
<span class="hljs-keyword">import</span> { <span class="hljs-title class_">Empty</span> } <span class="hljs-keyword">from</span> <span class="hljs-string">&#39;@cubui/cubui&#39;</span>;

<span class="hljs-keyword">const</span> app = <span class="hljs-title function_">createApp</span>();
app.<span class="hljs-title function_">use</span>(<span class="hljs-title class_">Empty</span>);
</code></pre><h3>Basic Usage</h3>`,6),i=a("pre",null,[a("code",{class:"language-vue"},[a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-empty"),s(),a("span",{class:"hljs-attr"},"description"),s("="),a("span",{class:"hljs-string"},'"no data"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-empty"),s(">")]),s(`
`),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
`)])],-1),j=a("h3",null,"Image Type",-1),g=a("pre",null,[a("code",{class:"language-vue"},[a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-tabs"),s(),a("span",{class:"hljs-attr"},"v-model"),s("="),a("span",{class:"hljs-string"},'"tabValue"'),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-tab-pane"),s(),a("span",{class:"hljs-attr"},"title"),s("="),a("span",{class:"hljs-string"},'"empty"'),s(">")]),s(`
      `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-empty"),s(),a("span",{class:"hljs-attr"},"image"),s("="),a("span",{class:"hljs-string"},'"empty"'),s(),a("span",{class:"hljs-attr"},"description"),s("="),a("span",{class:"hljs-string"},'"no cotent"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-empty"),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-tab-pane"),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-tab-pane"),s(),a("span",{class:"hljs-attr"},"title"),s("="),a("span",{class:"hljs-string"},'"error"'),s(">")]),s(`
      `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-empty"),s(),a("span",{class:"hljs-attr"},"image"),s("="),a("span",{class:"hljs-string"},'"error"'),s(),a("span",{class:"hljs-attr"},"description"),s("="),a("span",{class:"hljs-string"},'"error"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-empty"),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-tab-pane"),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-tab-pane"),s(),a("span",{class:"hljs-attr"},"title"),s("="),a("span",{class:"hljs-string"},'"no network"'),s(">")]),s(`
      `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-empty"),s(),a("span",{class:"hljs-attr"},"image"),s("="),a("span",{class:"hljs-string"},'"network"'),s(),a("span",{class:"hljs-attr"},"description"),s("="),a("span",{class:"hljs-string"},'"network"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-empty"),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-tab-pane"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-tabs"),s(">")]),s(`
`),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
`),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"script"),s(),a("span",{class:"hljs-attr"},"setup"),s(">")]),a("span",{class:"language-javascript"},[s(`
`),a("span",{class:"hljs-keyword"},"import"),s(" { ref } "),a("span",{class:"hljs-keyword"},"from"),s(),a("span",{class:"hljs-string"},"'vue'"),s(`;
`),a("span",{class:"hljs-keyword"},"const"),s(" tabValue = "),a("span",{class:"hljs-title function_"},"ref"),s("("),a("span",{class:"hljs-number"},"0"),s(`);
`)]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"script"),s(">")]),s(`
`)])],-1),u=a("h3",null,"Custom Image",-1),b=a("pre",null,[a("code",{class:"language-vue"},[a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-empty"),s(`
    `),a("span",{class:"hljs-attr"},"image"),s("="),a("span",{class:"hljs-string"},'"https://static-ftcms.kakusoft.com/p/files/61a9e3313985005b3958672e.png"'),s(`
    `),a("span",{class:"hljs-attr"},"description"),s("="),a("span",{class:"hljs-string"},'"Description"'),s(`
  >`)]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-empty"),s(">")]),s(`
`),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
`)])],-1),y=a("h3",null,"Bottom Content",-1),I=a("pre",null,[a("code",{class:"language-vue"},[a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-empty"),s(),a("span",{class:"hljs-attr"},"image"),s("="),a("span",{class:"hljs-string"},'"error"'),s(),a("span",{class:"hljs-attr"},"description"),s("="),a("span",{class:"hljs-string"},'"Failed to load"'),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"div"),s(),a("span",{class:"hljs-attr"},"style"),s("="),a("span",{class:"hljs-string"},'"margin-top: 10px"'),s(">")]),s(`
      `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-button"),s(),a("span",{class:"hljs-attr"},"icon"),s("="),a("span",{class:"hljs-string"},'"refresh"'),s(),a("span",{class:"hljs-attr"},"type"),s("="),a("span",{class:"hljs-string"},'"primary"'),s(">")]),s("Retry"),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-button"),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"div"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-empty"),s(">")]),s(`
`),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
`)])],-1),_=e('<h2>Empty</h2><h3>Props</h3><table><thead><tr><th>Attribute</th><th>Description</th><th>Type</th><th>Default</th></tr></thead><tbody><tr><td>image</td><td>Image type, can be set to <code class="">empty</code>, <code class="">error</code>, <code class="">network</code> or image <code class="">URL</code></td><td>string</td><td><code class="">empty</code></td></tr><tr><td>image-size</td><td>Image size</td><td>number | string</td><td><code class="">-</code></td></tr><tr><td>description</td><td>Description</td><td>string</td><td><code class="">-</code></td></tr></tbody></table><h3>Slots</h3><table><thead><tr><th>Name</th><th>Description</th></tr></thead><tbody><tr><td>default</td><td>Custom bottom content</td></tr><tr><td>image</td><td>Custom image</td></tr><tr><td>description</td><td>Custom description</td></tr></tbody></table><h2>Theming</h2><h3>CSS Variables</h3><p>The component provides the following CSS variables, which can be used to customize styles. Please refer to <a href="#/en-US/component/configprovider">ConfigProvider component</a>.</p><table><thead><tr><th>Name</th><th>Default Value</th></tr></thead><tbody><tr><td>--cub-empty-padding</td><td><em>32px 0</em></td></tr><tr><td>--cub-empty-image-size</td><td><em>170px</em></td></tr><tr><td>--cub-empty-description-margin-top</td><td><em>4px</em></td></tr><tr><td>--cub-empty-description-color</td><td><em>#666666</em></td></tr><tr><td>--cub-empty-description-font-size</td><td><em>14px</em></td></tr><tr><td>--cub-empty-description-line-height</td><td><em>20px</em></td></tr><tr><td>--cub-empty-description-padding</td><td><em>0 40px</em></td></tr></tbody></table>',9),x={},C="",G=p({__name:"doc.en-US",setup(v,{expose:c}){return c({frontmatter:{},excerpt:void 0}),(k,f)=>{const t=d("demo-block");return r(),h("div",o,[m,l(t,{"data-type":"vue","data-value":"PHRlbXBsYXRlPgogIDxjdWItZW1wdHkgZGVzY3JpcHRpb249Im5vIGRhdGEiPjwvySI+Cjwvyjw="},{default:n(()=>[i]),_:1}),j,l(t,{"data-type":"vue","data-value":"PHRlbXBsYXRlPgogIDxjdWItdGFicyB2LW1vZGVsPSJ0YWJWYWx1ZSLEIMoiLXBhbmUgdGl0bGU9ImVtcHR5xyHHI8UTIGltYWfJICBkZXNjcmlwdGlvbj0ibm8gY290ZW50Ij48L8kyx2XFEchm3Hlycm9y3HnFIM55xzTfddt1bm8gbmV0d29ya9t6yCLOfMk4337EFMkScz4KPC/qAaY8xlAgc2V0dXA+CmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSc7CmNvbnN0IOgBwSA9xCMoMCk7CjwvxkQ+Cg=="},{default:n(()=>[g]),_:1}),u,l(t,{"data-type":"vue","data-value":"PHRlbXBsYXRlPgogIDxjdWItZW1wdHkKICAgIGltYWdlPSJodHRwczovL3N0YXRpYy1mdGNtcy5rYWt1c29mdC5jb20vcC9maWxlcy82MWE5ZTMzMTM5ODUwMDViMzk1ODY3MmUucG5nIsVTZGVzY3JpcHRpb249IkTKDcQePjwv6QCAPgo8L+oAmg=="},{default:n(()=>[b]),_:1}),y,l(t,{"data-type":"vue","data-value":"PHRlbXBsYXRlPgogIDxjdWItZW1wdHkgaW1hZ2U9ImVycm9yIiBkZXNjcmlwdGlvbj0iRmFpbGVkIHRvIGxvYWQixDkgIDxkaXYgc3R5bGU9Im1hcmdpbi10b3A6IDEwcHjHI8dgYnV0dG9uIGljxExyZWZyZXNoIiB0eXBlPSJwcmltYXJ5Ij5SZXRyeTwvyjDHZi9kaXbEC8Yb5QCrPgo8L+oAxQ=="},{default:n(()=>[I]),_:1}),_])}}});export{G as default,C as excerpt,x as frontmatter};
