import{d as p,r as h,b as o,k as n,w as l,aq as c,e as a,o as d,l as s}from"./style_icon.js";const i={class:"markdown-body"},j=c(`<h1>Sticky</h1><h3>Intro</h3><p>Use fixed positioning to achieve a ceiling effect similar to <code class="">position: sticky</code>.</p><h3>Install</h3><pre><code class="language-js"><span class="hljs-keyword">import</span> { createApp } <span class="hljs-keyword">from</span> <span class="hljs-string">&#39;vue&#39;</span>;
<span class="hljs-keyword">import</span> { <span class="hljs-title class_">Sticky</span> } <span class="hljs-keyword">from</span> <span class="hljs-string">&#39;@cubui/cubui&#39;</span>;

<span class="hljs-keyword">const</span> app = <span class="hljs-title function_">createApp</span>();
app.<span class="hljs-title function_">use</span>(<span class="hljs-title class_">Sticky</span>);
</code></pre><h3>Basic Usage</h3>`,6),r=a("pre",null,[a("code",{class:"language-vue"},[a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"div"),s(),a("span",{class:"hljs-attr"},"style"),s("="),a("span",{class:"hljs-string"},'"height: 200vh; padding-top: 100px;"'),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-sticky"),s(">")]),s(`
      `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-button"),s(),a("span",{class:"hljs-attr"},"type"),s("="),a("span",{class:"hljs-string"},'"primary"'),s(">")]),s("Ceiling button"),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-button"),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-sticky"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"div"),s(">")]),s(`
`),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
`)])],-1),g=a("h3",null,"Ceiling distance",-1),m=a("pre",null,[a("code",{class:"language-vue"},[a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"div"),s(),a("span",{class:"hljs-attr"},"style"),s("="),a("span",{class:"hljs-string"},'"height: 200vh; padding-top: 200px;"'),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-sticky"),s(),a("span",{class:"hljs-attr"},"top"),s("="),a("span",{class:"hljs-string"},'"120"'),s(">")]),s(`
      `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-button"),s(),a("span",{class:"hljs-attr"},"type"),s("="),a("span",{class:"hljs-string"},'"primary"'),s(">")]),s("Ceiling button distance 120px"),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-button"),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-sticky"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"div"),s(">")]),s(`
`),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
`)])],-1),u=a("h3",null,"Specify container",-1),b=a("pre",null,[a("code",{class:"language-vue"},[a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"div"),s(),a("span",{class:"hljs-attr"},"style"),s("="),a("span",{class:"hljs-string"},'"height: 200vh; padding-top: 100px"'),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"div"),s(),a("span",{class:"hljs-attr"},"style"),s("="),a("span",{class:"hljs-string"},'"width: 100%; height: 150px; background: pink"'),s(),a("span",{class:"hljs-attr"},"ref"),s("="),a("span",{class:"hljs-string"},'"container"'),s(">")]),s(`
      `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-sticky"),s(),a("span",{class:"hljs-attr"},"top"),s("="),a("span",{class:"hljs-string"},'"20"'),s(),a("span",{class:"hljs-attr"},":container"),s("="),a("span",{class:"hljs-string"},'"container"'),s(">")]),s(`
        `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-button"),s(),a("span",{class:"hljs-attr"},"type"),s("="),a("span",{class:"hljs-string"},'"info"'),s(">")]),s("Container"),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-button"),s(">")]),s(`
      `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-sticky"),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"div"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"div"),s(">")]),s(`
`),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
`),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"script"),s(),a("span",{class:"hljs-attr"},"setup"),s(">")]),a("span",{class:"language-javascript"},[s(`
`),a("span",{class:"hljs-keyword"},"import"),s(" { ref } "),a("span",{class:"hljs-keyword"},"from"),s(),a("span",{class:"hljs-string"},"'vue'"),s(`;
`),a("span",{class:"hljs-keyword"},"const"),s(" container = "),a("span",{class:"hljs-title function_"},"ref"),s("("),a("span",{class:"hljs-literal"},"null"),s(`);
`)]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"script"),s(">")]),s(`
`)])],-1),v=a("h3",null,"Suction distance",-1),y=a("pre",null,[a("code",{class:"language-vue"},[a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"div"),s(),a("span",{class:"hljs-attr"},"style"),s("="),a("span",{class:"hljs-string"},'"height: 100vh; padding-top: 100vh"'),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-sticky"),s(),a("span",{class:"hljs-attr"},"bottom"),s("="),a("span",{class:"hljs-string"},'"50"'),s(),a("span",{class:"hljs-attr"},"position"),s("="),a("span",{class:"hljs-string"},'"bottom"'),s(">")]),s(`
      `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-button"),s(),a("span",{class:"hljs-attr"},"type"),s("="),a("span",{class:"hljs-string"},'"primary"'),s(">")]),s("Suction distance 50px"),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-button"),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-sticky"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"div"),s(">")]),s(`
`),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
`)])],-1),x=c('<h2>API</h2><h3>Props</h3><table><thead><tr><th>Attribute</th><th>Description</th><th>Type</th><th>Default</th></tr></thead><tbody><tr><td>position</td><td>Adsorption position（<code class="">top</code>、<code class="">bottom</code>）</td><td>string</td><td><code class="">top</code></td></tr><tr><td>top</td><td>Ceiling distance, enable when <code class="">position = top</code></td><td>number</td><td><code class="">0</code></td></tr><tr><td>bottom</td><td>Suction distance, enable when <code class="">position = bottom</code></td><td>number</td><td><code class="">0</code></td></tr><tr><td>container</td><td>The &#39;HTML&#39; node of the container</td><td>Element</td><td>-</td></tr><tr><td>z-index</td><td>Level of adsorption</td><td>number</td><td><code class="">99</code></td></tr></tbody></table><h3>Events</h3><table><thead><tr><th>Event</th><th>Description</th><th>Arguments</th></tr></thead><tbody><tr><td>change</td><td>Triggered when the adsorption state changes</td><td><code class="">fixed: boolean</code></td></tr></tbody></table>',5),R={},H="",f=p({__name:"doc.en-US",setup(I,{expose:e}){return e({frontmatter:{},excerpt:void 0}),(_,w)=>{const t=h("demo-block");return d(),o("div",i,[j,n(t,{"data-type":"vue","data-value":"PHRlbXBsYXRlPgogIDxkaXYgc3R5bGU9ImhlaWdodDogMjAwdmg7IHBhZGRpbmctdG9wOiAxMDBweDsixDMgIDxjdWItc3RpY2t5xhHHE2J1dHRvbiB0eXBlPSJwcmltYXJ5Ij5DZWlsaW5nIMYePC/KKsdOxRLKTzwvZGl2Pgo8L+oAqA=="},{default:l(()=>[r]),_:1}),g,n(t,{"data-type":"vue","data-value":"PHRlbXBsYXRlPgogIDxkaXYgc3R5bGU9ImhlaWdodDogMjAwdmg7IHBhZGRpbmctdG9wxRRweDsixDMgIDxjdWItc3RpY2t5IHRvcD0iMTIwxxvHHWJ1dHRvbiB0eXBlPSJwcmltYXJ5Ij5DZWlsaW5nIMceZGlzdGFuY2UgMTIwcHg8L8o5x2fFEsZoxBI8L2Rpdj4KPC/qAME="},{default:l(()=>[m]),_:1}),u,n(t,{"data-type":"vue","data-value":"PHRlbXBsYXRlPgogIDxkaXYgc3R5bGU9ImhlaWdodDogMjAwdmg7IHBhZGRpbmctdG9wOiAxMDBweCLEMs40d2lkdGjFHyU7IMhBMTUwcHg7IGJhY2tncm91bmQ6IHBpbmsiIHJlZj0iY29udGFpbmVyx08gIDxjdWItc3RpY2t5IHRvcD0iMjAiIDrJKNQzxzVidXR0b24gdHlwZT0iaW5mbyI+Q8gsPC/KIslqxRTGa8YUPC9kaXbEC8cJPC/qAR88c2NyaXB0IHNldHVwPgppbXBvcnQge+QAxyB9IGZyb20gJ3Z1ZSc7CmNvbnN0IOkApyA9xCQobnVsbCk7Cjwvxkg+Cg=="},{default:l(()=>[b]),_:1}),v,n(t,{"data-type":"vue","data-value":"PHRlbXBsYXRlPgogIDxkaXYgc3R5bGU9ImhlaWdodDogMTAwdmg7IHBhZGRpbmctdG9wxxQixDIgIDxjdWItc3RpY2t5IGJvdHRvbT0iNTAiIHBvc2l0aW9uPSLGFscvxzFidXR0b24gdHlwZT0icHJpbWFyeSI+U3VjxDMgZGlzdGFuY2UgNTBweDwvyjHHc8USxnTEEjwvZGl2Pgo8L+oAzA=="},{default:l(()=>[y]),_:1}),x])}}});export{f as default,H as excerpt,R as frontmatter};
