import{d as h,r as e,b as d,k as n,w as l,aq as c,e as a,l as s,o as i}from"./style_icon.js";const r={class:"markdown-body"},m=c(`<h1>Icon</h1><h3>Intro</h3><p>Install the <a href="https://github.com/cubfe/cubui-icons">@cubfe/icons-vue</a> package independently. Two usage modes are provided (SVG on-demand usage and IconFont full usage).</p><h3>Install</h3><pre><code class="language-bash">npm i --save @cubfe/icons-vue
</code></pre><h2>Use: SVG import on demand</h2><p>Use mode of on-demand loading components, see @cubfe/icons-vue/dist/types/index.d.ts</p><pre><code class="language-js"><span class="hljs-keyword">import</span> { <span class="hljs-title class_">Add</span> } <span class="hljs-keyword">from</span> <span class="hljs-string">&#39;@cubfe/icons-vue&#39;</span>;
<span class="hljs-comment">// template</span>
<span class="language-xml"><span class="hljs-tag">&lt;<span class="hljs-name">Add</span> <span class="hljs-attr">color</span>=<span class="hljs-string">&quot;red&quot;</span> /&gt;</span></span>;
</code></pre>`,8),j=c(`<pre><code class="">The SVG used internally in the component library is
Loading,Location,Location,Selected,Close,Left,Service,Top,Right,CheckNormal,Checked,CheckDisabled,DownArrow,JoySmile,Image,ImageError,CloseCircle,MaskClose,Minus,Plus,Up,Under,Notice,CheckChecked,StarN,Tips,Loading1,TriangleUp,TriangleDown,Photograph,Failure,Trash,Link,Download
</code></pre><h3>Props</h3><table><thead><tr><th>Attribute</th><th>Description</th><th>Type</th><th>Default</th></tr></thead><tbody><tr><td>name</td><td>Icon name or URL</td><td>string</td><td>-</td></tr><tr><td>color</td><td>Icon color</td><td>string</td><td>-</td></tr><tr><td>width</td><td>Icon size , eg <code class="">20px</code> <code class="">2em</code> <code class="">2rem</code></td><td>string | object</td><td>-</td></tr><tr><td>height</td><td>Icon size , eg <code class="">20px</code> <code class="">2em</code> <code class="">2rem</code></td><td>string | object</td><td>-</td></tr></tbody></table><h3>Events</h3><table><thead><tr><th>Event</th><th>Description</th><th>Arguments</th></tr></thead><tbody><tr><td>click</td><td>Emitted when icon is clicked</td><td>event: Event</td></tr></tbody></table><h2>Use: Full use of IconFont</h2><pre><code class="language-ks">import { createApp } from &#39;vue&#39;;
import { IconFont } from &#39;@cubfe/icons-vue&#39;;
import &#39;@cubfe/icons-vue/dist/style_iconfont.css&#39;;
const app = createApp();
app.use(IconFont);
</code></pre><p>Use <code class="">name</code> prop to set icon name or icon URL.</p>`,8),g=a("pre",null,[a("code",{class:"language-html"},[a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"shop"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"gift"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(`
    `),a("span",{class:"hljs-attr"},"size"),s("="),a("span",{class:"hljs-string"},'"40"'),s(`
    `),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"https://oss.netconcepts.cn/website/wap/job-wap-icon-1.png"'),s(`
  >`)]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
`),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
`)])],-1),u=a("h3",null,"Icon Color",-1),b=a("p",null,[s("Use "),a("code",{class:""},"color"),s(" prop to set icon color.")],-1),I=a("pre",null,[a("code",{class:"language-html"},[a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"shop"'),s(),a("span",{class:"hljs-attr"},"color"),s("="),a("span",{class:"hljs-string"},'"#fa2c19"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"shop"'),s(),a("span",{class:"hljs-attr"},"color"),s("="),a("span",{class:"hljs-string"},'"#64b578"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"gift"'),s(),a("span",{class:"hljs-attr"},"color"),s("="),a("span",{class:"hljs-string"},'"#fa2c19"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
`),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
`)])],-1),f=a("h3",null,"Icon Size",-1),_=a("p",null,[s("Use "),a("code",{class:""},"size"),s(" prop to set icon size default unit is "),a("code",{class:""},"px"),s(" .")],-1),v=a("pre",null,[a("code",{class:"language-html"},[a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"shop"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"shop"'),s(),a("span",{class:"hljs-attr"},"size"),s("="),a("span",{class:"hljs-string"},'"24"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"shop"'),s(),a("span",{class:"hljs-attr"},"size"),s("="),a("span",{class:"hljs-string"},'"16"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
`),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
`)])],-1),y=a("h3",null,"Universal motion icons",-1),F=a("p",null,[s("Adding the specified class class can realize the dynamic effect of the picture. The default is to play once, and adding the "),a("code",{class:""},"cub-icon-am-infinite"),s(" class can realize the loop playback. By setting css, the delay interval before the animation starts, and how long the animation will be completed")],-1),w=a("pre",null,[a("code",{class:"language-html"},[a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"dou-arrow-up"'),s(),a("span",{class:"hljs-attr"},"class"),s("="),a("span",{class:"hljs-string"},'"cub-icon-am-jump cub-icon-am-infinite"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"star-fill-n"'),s(),a("span",{class:"hljs-attr"},"class"),s("="),a("span",{class:"hljs-string"},'"cub-icon-am-blink cub-icon-am-infinite"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"refresh2"'),s(),a("span",{class:"hljs-attr"},"class"),s("="),a("span",{class:"hljs-string"},'"cub-icon-am-rotate cub-icon-am-infinite"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"heart-fill"'),s(),a("span",{class:"hljs-attr"},"class"),s("="),a("span",{class:"hljs-string"},'"cub-icon-am-breathe cub-icon-am-infinite"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"microphone"'),s(),a("span",{class:"hljs-attr"},"class"),s("="),a("span",{class:"hljs-string"},'"cub-icon-am-flash cub-icon-am-infinite"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"download"'),s(),a("span",{class:"hljs-attr"},"class"),s("="),a("span",{class:"hljs-string"},'"cub-icon-am-bounce cub-icon-am-infinite"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"message"'),s(),a("span",{class:"hljs-attr"},"class"),s("="),a("span",{class:"hljs-string"},'"cub-icon-am-shake cub-icon-am-infinite"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
`),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`

`),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"style"),s(">")]),a("span",{class:"language-css"},[s(`
  `),a("span",{class:"hljs-selector-class"},".cub-icon"),s(` {
    `),a("span",{class:"hljs-attr"},"--animate-duration"),s(": "),a("span",{class:"hljs-number"},"1s"),s(`;
    `),a("span",{class:"hljs-attr"},"--animate-delay"),s(": "),a("span",{class:"hljs-number"},"0s"),s(`;
  }
`)]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"style"),s(">")]),s(`
`)])],-1),C=c('<h3>Props</h3><table><thead><tr><th>Attribute</th><th>Description</th><th>Type</th><th>Default</th></tr></thead><tbody><tr><td>name</td><td>Icon name or URL</td><td>string</td><td>-</td></tr><tr><td>color</td><td>Icon color</td><td>string</td><td>-</td></tr><tr><td>size</td><td>Icon size , eg <code class="">20px</code> <code class="">2em</code> <code class="">2rem</code></td><td>string | object</td><td>-</td></tr><tr><td>font-class-name</td><td>Custom icon font base class name</td><td>string</td><td><code class="">cubui-iconfont</code></td></tr><tr><td>class-prefix</td><td>Custom icon class name prefix for using custom icons</td><td>string</td><td><code class="">cub-icon</code></td></tr><tr><td>tag</td><td>HTML Tag of root element</td><td>string</td><td><code class="">i</code></td></tr></tbody></table><h3>Events</h3><table><thead><tr><th>Event</th><th>Description</th><th>Arguments</th></tr></thead><tbody><tr><td>click</td><td>Emitted when icon is clicked</td><td>event: Event</td></tr></tbody></table><h2>Use: other icons</h2><p>The number of icons provided by <code class="">@cubfe/icons-vue</code> itself is limited. If it cannot meet the needs, you can consider using a more versatile and larger number of icon libraries.</p><ul><li><p>Recommended icon format: SVG</p></li><li><p>Recommended icon library: <a href="https://iconify.design/">iconify</a>, which provides more than 150,000 open source icons.</p></li><li><p>Recommended icon scheme: <a href="https://github.com/antfu/unplugin-icons">unplugin-icons</a>, which provides a way to introduce <code class="">iconify</code> on demand.</p></li></ul>',7),W={},X="",S=h({__name:"doc.en-US",setup(x,{expose:o}){return o({frontmatter:{},excerpt:void 0}),(R,k)=>{const p=e("icon-demo"),t=e("demo-block");return i(),d("div",r,[m,n(p),j,n(t,{"data-type":"vue","data-value":"PHRlbXBsYXRlPgogIDxJY29uRm9udCBuYW1lPSJzaG9wIj48L8gX1CRnaWZ02SQKICAgIHNpemU9IjQwIsUOxjZodHRwczovL29zcy5uZXRjb25jZXB0cy5jbi93ZWJzaXRlL3dhcC9qb2Itd2FwLWljb24tMS5wbmfERc1uPC/qAMI="},{default:l(()=>[g]),_:1}),u,b,n(t,{"data-type":"vue","data-value":"PHRlbXBsYXRlPgogIDxJY29uRm9udCBuYW1lPSJzaG9wIiBjb2xvcj0iI2ZhMmMxOSI+PC/IJ980PSIjNjRiNTc43zQiZ2lmdN5oPC/qAKg="},{default:l(()=>[I]),_:1}),f,_,n(t,{"data-type":"vue","data-value":"PHRlbXBsYXRlPgogIDxJY29uRm9udCBuYW1lPSJzaG9wIj48L8gX2SQgc2l6ZT0iMjTfLs0uMTbOLjwv6gCM"},{default:l(()=>[v]),_:1}),y,F,n(t,{"data-type":"vue","data-value":"PHRlbXBsYXRlPgogIDxJY29uRm9udCBuYW1lPSJkb3UtYXJyb3ctdXAiIGNsYXNzPSJjdWItaWNvbi1hbS1qdW1wIMwRaW5maW5pdGUiPjwvyE3UWnN0YXItZmlsbC1u1VlibGlua99a1lpyZWZyZXNoMtVXcm90YXRl31jWWGhlYXJ05QCz1VpicmVhdGjfW9dbbWljcm9waG9uZdVbZmxhc2jfWdZZZG93bmxvYWTVV2JvdW5j/wCx11htZXNzYWf2AK5zaGFr31bFVjwv6gJ6CjxzdHls5QKDLsg6IHsKICAgIC0tYW5pbWF0ZS1kdXJhdGlvbjogMXM70BxlbGF5OiAwxRl9Cjwvx1A="},{default:l(()=>[w]),_:1}),C])}}});export{S as default,X as excerpt,W as frontmatter};
