import{d as p,r as h,b as d,k as l,w as n,aq as e,e as a,o as r,l as s}from"./style_icon.js";const o={class:"markdown-body"},j=e(`<h1>Empty 空状态</h1><h3>介绍</h3><p>空状态时的占位提示</p><h3>安装</h3><pre><code class="language-js"><span class="hljs-keyword">import</span> { createApp } <span class="hljs-keyword">from</span> <span class="hljs-string">&#39;vue&#39;</span>;
<span class="hljs-keyword">import</span> { <span class="hljs-title class_">Empty</span> } <span class="hljs-keyword">from</span> <span class="hljs-string">&#39;@cubui/cubui&#39;</span>;

<span class="hljs-keyword">const</span> app = <span class="hljs-title function_">createApp</span>();
app.<span class="hljs-title function_">use</span>(<span class="hljs-title class_">Empty</span>);
</code></pre><h3>基础用法</h3>`,6),m=a("pre",null,[a("code",{class:"language-vue"},[a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-empty"),s(),a("span",{class:"hljs-attr"},"description"),s("="),a("span",{class:"hljs-string"},'"无数据"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-empty"),s(">")]),s(`
`),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
`)])],-1),i=a("h3",null,"图片类型",-1),g=a("pre",null,[a("code",{class:"language-vue"},[a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-tabs"),s(),a("span",{class:"hljs-attr"},"v-model"),s("="),a("span",{class:"hljs-string"},'"tabValue"'),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-tab-pane"),s(),a("span",{class:"hljs-attr"},"title"),s("="),a("span",{class:"hljs-string"},'"无内容"'),s(">")]),s(`
      `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-empty"),s(),a("span",{class:"hljs-attr"},"image"),s("="),a("span",{class:"hljs-string"},'"empty"'),s(),a("span",{class:"hljs-attr"},"description"),s("="),a("span",{class:"hljs-string"},'"无内容"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-empty"),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-tab-pane"),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-tab-pane"),s(),a("span",{class:"hljs-attr"},"title"),s("="),a("span",{class:"hljs-string"},'"加载失败/错误"'),s(">")]),s(`
      `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-empty"),s(),a("span",{class:"hljs-attr"},"image"),s("="),a("span",{class:"hljs-string"},'"error"'),s(),a("span",{class:"hljs-attr"},"description"),s("="),a("span",{class:"hljs-string"},'"加载失败/错误"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-empty"),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-tab-pane"),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-tab-pane"),s(),a("span",{class:"hljs-attr"},"title"),s("="),a("span",{class:"hljs-string"},'"无网络"'),s(">")]),s(`
      `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-empty"),s(),a("span",{class:"hljs-attr"},"image"),s("="),a("span",{class:"hljs-string"},'"network"'),s(),a("span",{class:"hljs-attr"},"description"),s("="),a("span",{class:"hljs-string"},'"无网络"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-empty"),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-tab-pane"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-tabs"),s(">")]),s(`
`),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
`),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"script"),s(),a("span",{class:"hljs-attr"},"setup"),s(">")]),a("span",{class:"language-javascript"},[s(`
`),a("span",{class:"hljs-keyword"},"import"),s(" { ref } "),a("span",{class:"hljs-keyword"},"from"),s(),a("span",{class:"hljs-string"},"'vue'"),s(`;
`),a("span",{class:"hljs-keyword"},"const"),s(" tabValue = "),a("span",{class:"hljs-title function_"},"ref"),s("("),a("span",{class:"hljs-number"},"0"),s(`);
`)]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"script"),s(">")]),s(`
`)])],-1),u=a("h3",null,"自定义图片",-1),b=a("pre",null,[a("code",{class:"language-vue"},[a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-empty"),s(`
    `),a("span",{class:"hljs-attr"},"image"),s("="),a("span",{class:"hljs-string"},'"https://static-ftcms.kakusoft.com/p/files/61a9e3313985005b3958672e.png"'),s(`
    `),a("span",{class:"hljs-attr"},"description"),s("="),a("span",{class:"hljs-string"},'"描述文字"'),s(`
  >`)]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-empty"),s(">")]),s(`
`),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
`)])],-1),y=a("h3",null,"底部内容",-1),_=a("pre",null,[a("code",{class:"language-vue"},[a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-empty"),s(),a("span",{class:"hljs-attr"},"image"),s("="),a("span",{class:"hljs-string"},'"error"'),s(),a("span",{class:"hljs-attr"},"description"),s("="),a("span",{class:"hljs-string"},'"加载失败"'),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"div"),s(),a("span",{class:"hljs-attr"},"style"),s("="),a("span",{class:"hljs-string"},'"margin-top: 10px"'),s(">")]),s(`
      `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-button"),s(),a("span",{class:"hljs-attr"},"icon"),s("="),a("span",{class:"hljs-string"},'"refresh"'),s(),a("span",{class:"hljs-attr"},"type"),s("="),a("span",{class:"hljs-string"},'"primary"'),s(">")]),s("重试"),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-button"),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"div"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-empty"),s(">")]),s(`
`),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
`)])],-1),v=e('<h2>Empty</h2><h3>Props</h3><table><thead><tr><th>参数</th><th>说明</th><th>类型</th><th>默认值</th></tr></thead><tbody><tr><td>image</td><td>图片类型，可选值为 <code class="">empty</code>、<code class="">error</code>、<code class="">network</code>，支持传入图片 <code class="">URL</code></td><td>string</td><td><code class="">empty</code></td></tr><tr><td>image-size</td><td>图片大小，单位为 <code class="">px</code></td><td>number | string</td><td><code class="">-</code></td></tr><tr><td>description</td><td>图片下方的描述文字</td><td>string</td><td><code class="">-</code></td></tr></tbody></table><h3>Slots</h3><table><thead><tr><th>名称</th><th>说明</th></tr></thead><tbody><tr><td>default</td><td>自定义底部内容</td></tr><tr><td>image</td><td>自定义图片</td></tr><tr><td>description</td><td>自定义描述文字</td></tr></tbody></table><h2>主题定制</h2><h3>样式变量</h3><p>组件提供了下列 CSS 变量，可用于自定义样式，使用方法请参考 <a href="#/zh-CN/component/configprovider">ConfigProvider 组件</a>。</p><table><thead><tr><th>名称</th><th>默认值</th></tr></thead><tbody><tr><td>--cub-empty-padding</td><td><em>32px 0</em></td></tr><tr><td>--cub-empty-image-size</td><td><em>170px</em></td></tr><tr><td>--cub-empty-description-margin-top</td><td><em>4px</em></td></tr><tr><td>--cub-empty-description-color</td><td><em>#666666</em></td></tr><tr><td>--cub-empty-description-font-size</td><td><em>14px</em></td></tr><tr><td>--cub-empty-description-line-height</td><td><em>20px</em></td></tr><tr><td>--cub-empty-description-padding</td><td><em>0 40px</em></td></tr></tbody></table>',9),k={},w="",W=p({__name:"doc",setup(x,{expose:c}){return c({frontmatter:{},excerpt:void 0}),(I,f)=>{const t=h("demo-block");return r(),d("div",o,[j,l(t,{"data-type":"vue","data-value":"PHRlbXBsYXRlPgogIDxjdWItZW1wdHkgZGVzY3JpcHRpb249IuaXoOaVsOaNriI+PC/JJD4KPC/KPg=="},{default:n(()=>[m]),_:1}),i,l(t,{"data-type":"vue","data-value":"PHRlbXBsYXRlPgogIDxjdWItdGFicyB2LW1vZGVsPSJ0YWJWYWx1ZSLEIMoiLXBhbmUgdGl0bGU9IuaXoOWGheWuucclxydlbXB0eSBpbWFnZT0ixQ0iIGRlc2NyaXB0aW9uzTg8L8kyx2nFEchq233liqDovb3lpLHotKUv6ZSZ6K+v/ACHcnJvcu8Ah9VC/wCR/gEO572R57uc+wCHbmV0d29ya/IBEMg633/EFMkScz4KPC/qAcc8xlIgc2V0dXA+CmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSc7CmNvbnN0IOgB4iA9xCMoMCk7CjwvxkQ+Cg=="},{default:n(()=>[g]),_:1}),u,l(t,{"data-type":"vue","data-value":"PHRlbXBsYXRlPgogIDxjdWItZW1wdHkKICAgIGltYWdlPSJodHRwczovL3N0YXRpYy1mdGNtcy5rYWt1c29mdC5jb20vcC9maWxlcy82MWE5ZTMzMTM5ODUwMDViMzk1ODY3MmUucG5nIsVTZGVzY3JpcHRpb249IuaPj+i/sOaWh+Wtl8QfPjwv6QCBPgo8L+oAmw=="},{default:n(()=>[b]),_:1}),y,l(t,{"data-type":"vue","data-value":"PHRlbXBsYXRlPgogIDxjdWItZW1wdHkgaW1hZ2U9ImVycm9yIiBkZXNjcmlwdGlvbj0i5Yqg6L295aSx6LSlIsQ3ICA8ZGl2IHN0eWxlPSJtYXJnaW4tdG9wOiAxMHB4xyPHXmJ1dHRvbiBpY8RKcmVmcmVzaCIgdHlwZT0icHJpbWFyeSI+6YeN6K+VPC/KMcdnL2RpdsQLxhvlAKo+Cjwv6gDE"},{default:n(()=>[_]),_:1}),v])}}});export{W as default,w as excerpt,k as frontmatter};
