import{d as h,r as e,b as d,k as n,w as l,aq as c,e as a,l as s,o as i}from"./style_icon.js";const r={class:"markdown-body"},j=c(`<h1>Icon 图标</h1><h3>介绍</h3><p>独立安装 <a href="https://github.com/cubfe/cubui-icons">@cubfe/icons-vue</a> 图标组件包。提供两种使用方式（Svg 按需使用、IconFont 全量使用）。</p><h3>安装</h3><pre><code class="language-bash">npm i --save @cubfe/icons-vue
</code></pre><h2>方式一： SVG 按需使用</h2><p>按需加载组件使用方式，可选项见 @cubfe/icons-vue/dist/types/index.d.ts</p><pre><code class="language-js"><span class="hljs-keyword">import</span> { <span class="hljs-title class_">Add</span> } <span class="hljs-keyword">from</span> <span class="hljs-string">&#39;@cubfe/icons-vue&#39;</span>;
<span class="hljs-comment">// template</span>
<span class="language-xml"><span class="hljs-tag">&lt;<span class="hljs-name">Add</span> <span class="hljs-attr">color</span>=<span class="hljs-string">&quot;red&quot;</span> /&gt;</span></span>;
</code></pre>`,8),m=c(`<pre><code class="">其中组件库内部使用 SVG 为
Loading,Location,Location,Check,Close,Left,Service,Top,Right,CheckNormal,Checked,CheckDisabled,DownArrow,JoySmile,Image,ImageError,CloseCircle,MaskClose,Minus,Plus,Up,Under,Notice,CheckChecked,StarN,Tips,Loading1,TriangleUp,TriangleDown,Photograph,Failure,Trash,Link,Download
</code></pre><h3>Props</h3><table><thead><tr><th>参数</th><th>说明</th><th>类型</th><th>默认值</th></tr></thead><tbody><tr><td>name</td><td>图标名称或图片链接</td><td>string</td><td>-</td></tr><tr><td>color</td><td>图标颜色</td><td>string</td><td>-</td></tr><tr><td>width</td><td>图标大小，如 <code class="">20px</code> <code class="">2em</code> <code class="">2rem</code></td><td>string | object</td><td>-</td></tr><tr><td>height</td><td>图标大小，如 <code class="">20px</code> <code class="">2em</code> <code class="">2rem</code></td><td>string | object</td><td>-</td></tr></tbody></table><h3>Events</h3><table><thead><tr><th>事件名</th><th>说明</th><th>回调参数</th></tr></thead><tbody><tr><td>click</td><td>点击图标时触发</td><td>event: Event</td></tr></tbody></table><h2>方式二： IconFont 全量使用</h2><pre><code class="language-js"><span class="hljs-keyword">import</span> { createApp } <span class="hljs-keyword">from</span> <span class="hljs-string">&#39;vue&#39;</span>;
<span class="hljs-keyword">import</span> { <span class="hljs-title class_">IconFont</span> } <span class="hljs-keyword">from</span> <span class="hljs-string">&#39;@cubfe/icons-vue&#39;</span>;
<span class="hljs-keyword">import</span> <span class="hljs-string">&#39;@cubfe/icons-vue/dist/style_iconfont.css&#39;</span>;
<span class="hljs-keyword">const</span> app = <span class="hljs-title function_">createApp</span>();
app.<span class="hljs-title function_">use</span>(<span class="hljs-title class_">IconFont</span>);
</code></pre><p><code class="">Icon</code> 的 <code class="">name</code> 属性支持传入图标名称或图片链接。</p>`,8),g=a("pre",null,[a("code",{class:"language-html"},[a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"shop"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"gift"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(`
    `),a("span",{class:"hljs-attr"},"size"),s("="),a("span",{class:"hljs-string"},'"40"'),s(`
    `),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"https://oss.netconcepts.cn/website/wap/job-wap-icon-1.png"'),s(`
  >`)]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
`),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
`)])],-1),u=a("h4",null,"图标颜色",-1),b=a("p",null,[a("code",{class:""},"Icon"),s(" 的 "),a("code",{class:""},"color"),s(" 属性用来设置图标的颜色。")],-1),I=a("pre",null,[a("code",{class:"language-html"},[a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"shop"'),s(),a("span",{class:"hljs-attr"},"color"),s("="),a("span",{class:"hljs-string"},'"#fa2c19"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"shop"'),s(),a("span",{class:"hljs-attr"},"color"),s("="),a("span",{class:"hljs-string"},'"#64b578"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"gift"'),s(),a("span",{class:"hljs-attr"},"color"),s("="),a("span",{class:"hljs-string"},'"#fa2c19"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
`),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
`)])],-1),f=a("h4",null,"图标大小",-1),_=a("p",null,[a("code",{class:""},"Icon"),s(" 的 "),a("code",{class:""},"size"),s(" 属性用来设置图标的尺寸大小，默认单位为 "),a("code",{class:""},"px"),s("。")],-1),F=a("pre",null,[a("code",{class:"language-html"},[a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"shop"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"shop"'),s(),a("span",{class:"hljs-attr"},"size"),s("="),a("span",{class:"hljs-string"},'"24"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"shop"'),s(),a("span",{class:"hljs-attr"},"size"),s("="),a("span",{class:"hljs-string"},'"16"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
`),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
`)])],-1),v=a("h4",null,"通用动态图标",-1),w=a("p",null,[s("添加指定的 class 类就可以实现图片动态效果，默认是播放 1 次，添加 "),a("code",{class:""},"cub-icon-am-infinite"),s(" 类即可实现循环播放。通过设置 css 可实现动画启动前的延迟间隔、动画在多久时间内完成")],-1),y=a("pre",null,[a("code",{class:"language-html"},[a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"dou-arrow-up"'),s(),a("span",{class:"hljs-attr"},"class"),s("="),a("span",{class:"hljs-string"},'"cub-icon-am-jump cub-icon-am-infinite"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"star-fill-n"'),s(),a("span",{class:"hljs-attr"},"class"),s("="),a("span",{class:"hljs-string"},'"cub-icon-am-blink cub-icon-am-infinite"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"refresh2"'),s(),a("span",{class:"hljs-attr"},"class"),s("="),a("span",{class:"hljs-string"},'"cub-icon-am-rotate cub-icon-am-infinite"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"heart-fill"'),s(),a("span",{class:"hljs-attr"},"class"),s("="),a("span",{class:"hljs-string"},'"cub-icon-am-breathe cub-icon-am-infinite"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"microphone"'),s(),a("span",{class:"hljs-attr"},"class"),s("="),a("span",{class:"hljs-string"},'"cub-icon-am-flash cub-icon-am-infinite"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"download"'),s(),a("span",{class:"hljs-attr"},"class"),s("="),a("span",{class:"hljs-string"},'"cub-icon-am-bounce cub-icon-am-infinite"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"IconFont"),s(),a("span",{class:"hljs-attr"},"name"),s("="),a("span",{class:"hljs-string"},'"message"'),s(),a("span",{class:"hljs-attr"},"class"),s("="),a("span",{class:"hljs-string"},'"cub-icon-am-shake cub-icon-am-infinite"'),s(">")]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"IconFont"),s(">")]),s(`
`),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`

`),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"style"),s(">")]),a("span",{class:"language-css"},[s(`
  `),a("span",{class:"hljs-selector-class"},".cub-icon"),s(` {
    `),a("span",{class:"hljs-attr"},"--animate-duration"),s(": "),a("span",{class:"hljs-number"},"1s"),s(`;
    `),a("span",{class:"hljs-attr"},"--animate-delay"),s(": "),a("span",{class:"hljs-number"},"0s"),s(`;
  }
`)]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"style"),s(">")]),s(`
`)])],-1),C=c('<h3>Props</h3><table><thead><tr><th>参数</th><th>说明</th><th>类型</th><th>默认值</th></tr></thead><tbody><tr><td>name</td><td>图标名称或图片链接</td><td>string</td><td>-</td></tr><tr><td>color</td><td>图标颜色</td><td>string</td><td>-</td></tr><tr><td>size</td><td>图标大小，如 <code class="">20px</code> <code class="">2em</code> <code class="">2rem</code></td><td>string | object</td><td>-</td></tr><tr><td>font-class-name</td><td>自定义 <code class="">icon</code> 字体基础类名</td><td>string</td><td><code class="">cubui-iconfont</code></td></tr><tr><td>class-prefix</td><td>自定义 <code class="">icon</code> 类名前缀</td><td>string</td><td><code class="">cub-icon</code></td></tr><tr><td>tag</td><td><code class="">HTML</code> 标签</td><td>string</td><td><code class="">i</code></td></tr></tbody></table><h3>Events</h3><table><thead><tr><th>事件名</th><th>说明</th><th>回调参数</th></tr></thead><tbody><tr><td>click</td><td>点击图标时触发</td><td>event: Event</td></tr></tbody></table><h2>方式三：使用自定义图标库</h2><p><code class="">@cubfe/icons-vue</code> 本身提供的图标数量有限，如果不能满足需求，可以考虑使用通用性更强、数量更多的图标库。</p><ul><li><p>推荐图标格式：SVG</p></li><li><p>推荐图标库：<a href="https://iconify.design/">iconify</a>，它提供了超过 150,000 个开源图标。</p></li><li><p>推荐图标方案：<a href="https://github.com/antfu/unplugin-icons">unplugin-icons</a>，它提供了按需引入 <code class="">iconify</code> 的方式。</p></li></ul>',7),P={},R="",S=h({__name:"doc",setup(k,{expose:o}){return o({frontmatter:{},excerpt:void 0}),(x,W)=>{const p=e("icon-demo"),t=e("demo-block");return i(),d("div",r,[j,n(p),m,n(t,{"data-type":"vue","data-value":"PHRlbXBsYXRlPgogIDxJY29uRm9udCBuYW1lPSJzaG9wIj48L8gX1CRnaWZ02SQKICAgIHNpemU9IjQwIsUOxjZodHRwczovL29zcy5uZXRjb25jZXB0cy5jbi93ZWJzaXRlL3dhcC9qb2Itd2FwLWljb24tMS5wbmfERc1uPC/qAMI="},{default:l(()=>[g]),_:1}),u,b,n(t,{"data-type":"vue","data-value":"PHRlbXBsYXRlPgogIDxJY29uRm9udCBuYW1lPSJzaG9wIiBjb2xvcj0iI2ZhMmMxOSI+PC/IJ980PSIjNjRiNTc43zQiZ2lmdN5oPC/qAKg="},{default:l(()=>[I]),_:1}),f,_,n(t,{"data-type":"vue","data-value":"PHRlbXBsYXRlPgogIDxJY29uRm9udCBuYW1lPSJzaG9wIj48L8gX2SQgc2l6ZT0iMjTfLs0uMTbOLjwv6gCM"},{default:l(()=>[F]),_:1}),v,w,n(t,{"data-type":"vue","data-value":"PHRlbXBsYXRlPgogIDxJY29uRm9udCBuYW1lPSJkb3UtYXJyb3ctdXAiIGNsYXNzPSJjdWItaWNvbi1hbS1qdW1wIMwRaW5maW5pdGUiPjwvyE3UWnN0YXItZmlsbC1u1VlibGlua99a1lpyZWZyZXNoMtVXcm90YXRl31jWWGhlYXJ05QCz1VpicmVhdGjfW9dbbWljcm9waG9uZdVbZmxhc2jfWdZZZG93bmxvYWTVV2JvdW5j/wCx11htZXNzYWf2AK5zaGFr31bFVjwv6gJ6CjxzdHls5QKDLsg6IHsKICAgIC0tYW5pbWF0ZS1kdXJhdGlvbjogMXM70BxlbGF5OiAwxRl9Cjwvx1A="},{default:l(()=>[y]),_:1}),C])}}});export{S as default,R as excerpt,P as frontmatter};
