import{d as p,r,b as h,k as t,w as n,aq as c,e as a,o as d,l as s}from"./style_icon.js";const o={class:"markdown-body"},j=c(`<h1>Indicator 指示器</h1><h3>介绍</h3><p>显示一个任务或流程的进度，常用于开通流程。</p><h3>安装</h3><pre><code class="language-js"><span class="hljs-keyword">import</span> { createApp } <span class="hljs-keyword">from</span> <span class="hljs-string">&#39;vue&#39;</span>;
<span class="hljs-keyword">import</span> { <span class="hljs-title class_">Indicator</span> } <span class="hljs-keyword">from</span> <span class="hljs-string">&#39;@cubui/cubui&#39;</span>;

<span class="hljs-keyword">const</span> app = <span class="hljs-title function_">createApp</span>();
app.<span class="hljs-title function_">use</span>(<span class="hljs-title class_">Indicator</span>);
</code></pre><h3>基础用法</h3>`,6),i=a("pre",null,[a("code",{class:"language-vue"},[a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-cell"),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-indicator"),s(),a("span",{class:"hljs-attr"},":size"),s("="),a("span",{class:"hljs-string"},'"3"'),s(),a("span",{class:"hljs-attr"},":current"),s("="),a("span",{class:"hljs-string"},'"3"'),s(">")]),s("step1"),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-indicator"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-cell"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-cell"),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-row"),s(">")]),s(`
      `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-col"),s(),a("span",{class:"hljs-attr"},":span"),s("="),a("span",{class:"hljs-string"},'"12"'),s(">")]),s(`
        `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-button"),s(),a("span",{class:"hljs-attr"},"size"),s("="),a("span",{class:"hljs-string"},'"small"'),s(),a("span",{class:"hljs-attr"},"type"),s("="),a("span",{class:"hljs-string"},'"primary"'),s(">")]),s("主要按钮"),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-button"),s(">")]),s(`
      `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-col"),s(">")]),s(`
      `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-col"),s(),a("span",{class:"hljs-attr"},":span"),s("="),a("span",{class:"hljs-string"},'"12"'),s(">")]),s(`
        `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-indicator"),s(),a("span",{class:"hljs-attr"},"block"),s(),a("span",{class:"hljs-attr"},"align"),s("="),a("span",{class:"hljs-string"},'"right"'),s(),a("span",{class:"hljs-attr"},":size"),s("="),a("span",{class:"hljs-string"},'"6"'),s(),a("span",{class:"hljs-attr"},":current"),s("="),a("span",{class:"hljs-string"},'"5"'),s(">")]),s("step1"),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-indicator"),s(">")]),s(`
      `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-col"),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-row"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-cell"),s(">")]),s(`
`),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
`)])],-1),g=a("h3",null,"block 用法",-1),m=a("pre",null,[a("code",{class:"language-vue"},[a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-cell"),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-indicator"),s(),a("span",{class:"hljs-attr"},"block"),s(),a("span",{class:"hljs-attr"},"algin"),s("="),a("span",{class:"hljs-string"},'"center"'),s(),a("span",{class:"hljs-attr"},":size"),s("="),a("span",{class:"hljs-string"},'"6"'),s(),a("span",{class:"hljs-attr"},":current"),s("="),a("span",{class:"hljs-string"},'"5"'),s(">")]),s("step1"),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-indicator"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-cell"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-cell"),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-indicator"),s(),a("span",{class:"hljs-attr"},"block"),s(),a("span",{class:"hljs-attr"},"align"),s("="),a("span",{class:"hljs-string"},'"left"'),s(),a("span",{class:"hljs-attr"},":size"),s("="),a("span",{class:"hljs-string"},'"6"'),s(),a("span",{class:"hljs-attr"},":current"),s("="),a("span",{class:"hljs-string"},'"1"'),s(">")]),s("step1"),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-indicator"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-cell"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-cell"),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-indicator"),s(),a("span",{class:"hljs-attr"},"block"),s(),a("span",{class:"hljs-attr"},"align"),s("="),a("span",{class:"hljs-string"},'"right"'),s(),a("span",{class:"hljs-attr"},":size"),s("="),a("span",{class:"hljs-string"},'"6"'),s(),a("span",{class:"hljs-attr"},":current"),s("="),a("span",{class:"hljs-string"},'"5"'),s(">")]),s("step1"),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-indicator"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-cell"),s(">")]),s(`
`),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
`)])],-1),u=a("h3",null,"不补 0",-1),b=a("pre",null,[a("code",{class:"language-vue"},[a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-cell"),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-indicator"),s(),a("span",{class:"hljs-attr"},":fill-zero"),s("="),a("span",{class:"hljs-string"},'"false"'),s(),a("span",{class:"hljs-attr"},":size"),s("="),a("span",{class:"hljs-string"},'"6"'),s(),a("span",{class:"hljs-attr"},":current"),s("="),a("span",{class:"hljs-string"},'"5"'),s(">")]),s("step1"),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-indicator"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-cell"),s(">")]),s(`
`),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
`)])],-1),_=c('<h2>API</h2><h3>Props</h3><table><thead><tr><th>参数</th><th>说明</th><th>类型</th><th>默认值</th></tr></thead><tbody><tr><td>current</td><td>当前步骤</td><td>number</td><td><code class="">1</code></td></tr><tr><td>size</td><td>步骤长度</td><td>number</td><td><code class="">3</code></td></tr><tr><td>block</td><td>是否启用块级布局</td><td>boolean</td><td><code class="">false</code></td></tr><tr><td>align</td><td>对齐方式，仅在 <code class="">block</code> 为 <code class="">true</code> 时生效, 可选值 <code class="">left</code>, <code class="">right</code>, <code class="">center</code></td><td>string</td><td><code class="">left</code></td></tr><tr><td>fill-zero</td><td>单数前面是否补 0</td><td>boolean</td><td><code class="">true</code></td></tr></tbody></table><h2>主题定制</h2><h3>样式变量</h3><p>组件提供了下列 CSS 变量，可用于自定义样式，使用方法请参考 <a href="#/zh-CN/component/configprovider">ConfigProvider 组件</a>。</p><table><thead><tr><th>名称</th><th>默认值</th></tr></thead><tbody><tr><td>--cub-indicator-bg-color</td><td><em>var(--cub-primary-color)</em></td></tr><tr><td>--cub-indicator-dot-color</td><td><em>var(--cub-disable-color)</em></td></tr><tr><td>--cub-indicator-color</td><td><em>var(--cub-white)</em></td></tr><tr><td>--cub-indicator-size</td><td><em>18px</em></td></tr><tr><td>--cub-indicator-dot-size</td><td><em>calc(var(--cub-indicator-size) / 3)</em></td></tr><tr><td>--cub-indicator-border-size</td><td><em>calc(var(--cub-indicator-size)+ 2)</em></td></tr><tr><td>--cub-indicator-number-font-size</td><td><em>10px</em></td></tr></tbody></table>',7),x={},w="",z=p({__name:"doc",setup(I,{expose:e}){return e({frontmatter:{},excerpt:void 0}),(f,y)=>{const l=r("demo-block");return d(),h("div",o,[j,t(l,{"data-type":"vue","data-value":"PHRlbXBsYXRlPgogIDxjdWItY2VsbMQNxw9pbmRpY2F0b3IgOnNpemU9IjMiIDpjdXJyZW50xA0+c3RlcDE8L80sxU3FE8hO1Ftyb3fGDsgfb2wgOnNwYW49IjEyIsgbxx1idXR0b24g5gCEc21hbGwiIHR5cGU9InByaW1hcnkiPuS4u+imgeaMiemSrsZ+xjXJZcUUY2/nAITfdu8A/mJsb2NrIGFsaWduPSJyaWdodCLoARI27AESNfoBEvMAhMYP5wEJ7AEyPC/qAZk="},{default:n(()=>[i]),_:1}),g,t(l,{"data-type":"vue","data-value":"PHRlbXBsYXRlPgogIDxjdWItY2VsbMQNxw9pbmRpY2F0b3IgYmxvY2sgYWxnaW49ImNlbnRlciIgOnNpemU9IjYiIDpjdXJyZW50PSI1Ij5zdGVwMTwvzUHFYsUTyGPfcMdwaWduPSJsZWZ01m4x327fbtVucmlnaNdv/wDdyGI8L+oBWQ=="},{default:n(()=>[m]),_:1}),u,t(l,{"data-type":"vue","data-value":"PHRlbXBsYXRlPgogIDxjdWItY2VsbMQNxw9pbmRpY2F0b3IgOmZpbGwtemVybz0iZmFsc2UiIDpzaXplPSI2IiA6Y3VycmVudD0iNSI+c3RlcDE8L80/xWDFE8ZhPC/Keg=="},{default:n(()=>[b]),_:1}),_])}}});export{z as default,w as excerpt,x as frontmatter};
