import{d as p,r as h,b as d,k as l,w as n,aq as c,e as a,o,l as s}from"./style_icon.js";const j={class:"markdown-body"},i=c(`<h1>Sticky 粘性布局</h1><h3>介绍</h3><p>使用 fixed 定位实现的类似 <code class="">position: sticky</code> 的吸顶效果。</p><h3>安装</h3><pre><code class="language-js"><span class="hljs-keyword">import</span> { createApp } <span class="hljs-keyword">from</span> <span class="hljs-string">&#39;vue&#39;</span>;
<span class="hljs-keyword">import</span> { <span class="hljs-title class_">Sticky</span> } <span class="hljs-keyword">from</span> <span class="hljs-string">&#39;@cubui/cubui&#39;</span>;

<span class="hljs-keyword">const</span> app = <span class="hljs-title function_">createApp</span>();
app.<span class="hljs-title function_">use</span>(<span class="hljs-title class_">Sticky</span>);
</code></pre><h3>基础用法</h3>`,6),r=a("pre",null,[a("code",{class:"language-vue"},[a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"div"),s(),a("span",{class:"hljs-attr"},"style"),s("="),a("span",{class:"hljs-string"},'"height: 200vh; padding-top: 100px;"'),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-sticky"),s(">")]),s(`
      `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-button"),s(),a("span",{class:"hljs-attr"},"type"),s("="),a("span",{class:"hljs-string"},'"primary"'),s(">")]),s("吸顶按钮"),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-button"),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-sticky"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"div"),s(">")]),s(`
`),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
`)])],-1),g=a("h3",null,"吸顶距离",-1),m=a("pre",null,[a("code",{class:"language-vue"},[a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"div"),s(),a("span",{class:"hljs-attr"},"style"),s("="),a("span",{class:"hljs-string"},'"height: 200vh; padding-top: 200px;"'),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-sticky"),s(),a("span",{class:"hljs-attr"},"top"),s("="),a("span",{class:"hljs-string"},'"120"'),s(">")]),s(`
      `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-button"),s(),a("span",{class:"hljs-attr"},"type"),s("="),a("span",{class:"hljs-string"},'"primary"'),s(">")]),s("吸顶距离120px"),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-button"),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-sticky"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"div"),s(">")]),s(`
`),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
`)])],-1),b=a("h3",null,"指定容器",-1),u=a("pre",null,[a("code",{class:"language-vue"},[a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"div"),s(),a("span",{class:"hljs-attr"},"style"),s("="),a("span",{class:"hljs-string"},'"height: 200vh; padding-top: 100px"'),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"div"),s(),a("span",{class:"hljs-attr"},"style"),s("="),a("span",{class:"hljs-string"},'"width: 100%; height: 150px; background: pink"'),s(),a("span",{class:"hljs-attr"},"ref"),s("="),a("span",{class:"hljs-string"},'"container"'),s(">")]),s(`
      `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-sticky"),s(),a("span",{class:"hljs-attr"},"top"),s("="),a("span",{class:"hljs-string"},'"20"'),s(),a("span",{class:"hljs-attr"},":container"),s("="),a("span",{class:"hljs-string"},'"container"'),s(">")]),s(`
        `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-button"),s(),a("span",{class:"hljs-attr"},"type"),s("="),a("span",{class:"hljs-string"},'"info"'),s(">")]),s("指定容器"),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-button"),s(">")]),s(`
      `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-sticky"),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"div"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"div"),s(">")]),s(`
`),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
`),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"script"),s(),a("span",{class:"hljs-attr"},"setup"),s(">")]),a("span",{class:"language-javascript"},[s(`
`),a("span",{class:"hljs-keyword"},"import"),s(" { ref } "),a("span",{class:"hljs-keyword"},"from"),s(),a("span",{class:"hljs-string"},"'vue'"),s(`;
`),a("span",{class:"hljs-keyword"},"const"),s(" container = "),a("span",{class:"hljs-title function_"},"ref"),s("("),a("span",{class:"hljs-literal"},"null"),s(`);
`)]),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"script"),s(">")]),s(`
`)])],-1),y=a("h3",null,"吸底距离",-1),v=a("pre",null,[a("code",{class:"language-vue"},[a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"div"),s(),a("span",{class:"hljs-attr"},"style"),s("="),a("span",{class:"hljs-string"},'"height: 100vh; padding-top: 100vh"'),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-sticky"),s(),a("span",{class:"hljs-attr"},"bottom"),s("="),a("span",{class:"hljs-string"},'"50"'),s(),a("span",{class:"hljs-attr"},"position"),s("="),a("span",{class:"hljs-string"},'"bottom"'),s(">")]),s(`
      `),a("span",{class:"hljs-tag"},[s("<"),a("span",{class:"hljs-name"},"cub-button"),s(),a("span",{class:"hljs-attr"},"type"),s("="),a("span",{class:"hljs-string"},'"primary"'),s(">")]),s("吸底距离 50px"),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-button"),s(">")]),s(`
    `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"cub-sticky"),s(">")]),s(`
  `),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"div"),s(">")]),s(`
`),a("span",{class:"hljs-tag"},[s("</"),a("span",{class:"hljs-name"},"template"),s(">")]),s(`
`)])],-1),x=c('<h2>API</h2><h3>Props</h3><table><thead><tr><th>参数</th><th>说明</th><th>类型</th><th>默认值</th></tr></thead><tbody><tr><td>position</td><td>吸附位置（<code class="">top</code>、<code class="">bottom</code>）</td><td>string</td><td><code class="">top</code></td></tr><tr><td>top</td><td>吸顶距离，<code class="">position</code> 为 <code class="">top</code> 时生效</td><td>number</td><td><code class="">0</code></td></tr><tr><td>bottom</td><td>吸底距离，<code class="">position</code> 为 <code class="">bottom</code> 时生效</td><td>number</td><td><code class="">0</code></td></tr><tr><td>container</td><td>容器的 <code class="">HTML</code> 节点</td><td>Element</td><td>-</td></tr><tr><td>z-index</td><td>吸附时的层级</td><td>number</td><td><code class="">99</code></td></tr></tbody></table><h3>Events</h3><table><thead><tr><th>事件名</th><th>说明</th><th>回调参数</th></tr></thead><tbody><tr><td>change</td><td>吸附状态改变时触发</td><td><code class="">fixed: boolean</code></td></tr></tbody></table>',5),H={},R="",B=p({__name:"doc",setup(I,{expose:e}){return e({frontmatter:{},excerpt:void 0}),(k,_)=>{const t=h("demo-block");return o(),d("div",j,[i,l(t,{"data-type":"vue","data-value":"PHRlbXBsYXRlPgogIDxkaXYgc3R5bGU9ImhlaWdodDogMjAwdmg7IHBhZGRpbmctdG9wOiAxMDBweDsixDMgIDxjdWItc3RpY2t5xhHHE2J1dHRvbiB0eXBlPSJwcmltYXJ5Ij7lkLjpobbmjInpkq48L8oox0zFEspNPC9kaXY+Cjwv6gCm"},{default:n(()=>[r]),_:1}),g,l(t,{"data-type":"vue","data-value":"PHRlbXBsYXRlPgogIDxkaXYgc3R5bGU9ImhlaWdodDogMjAwdmg7IHBhZGRpbmctdG9wxRRweDsixDMgIDxjdWItc3RpY2t5IHRvcD0iMTIwxxvHHWJ1dHRvbiB0eXBlPSJwcmltYXJ5Ij7lkLjpobbot53nprsxMjBweDwvyi3HW8USxlzEEjwvZGl2Pgo8L+oAtQ=="},{default:n(()=>[m]),_:1}),b,l(t,{"data-type":"vue","data-value":"PHRlbXBsYXRlPgogIDxkaXYgc3R5bGU9ImhlaWdodDogMjAwdmg7IHBhZGRpbmctdG9wOiAxMDBweCLEMs40d2lkdGjFHyU7IMhBMTUwcHg7IGJhY2tncm91bmQ6IHBpbmsiIHJlZj0iY29udGFpbmVyx08gIDxjdWItc3RpY2t5IHRvcD0iMjAiIDrJKNQzxzVidXR0b24gdHlwZT0iaW5mbyI+5oyH5a6a5a655ZmoPC/KJcltxRTGbsYUPC9kaXbEC8cJPC/qASI8c2NyaXB0IHNldHVwPgppbXBvcnQge+QAyiB9IGZyb20gJ3Z1ZSc7CmNvbnN0IOkAqiA9xCQobnVsbCk7Cjwvxkg+Cg=="},{default:n(()=>[u]),_:1}),y,l(t,{"data-type":"vue","data-value":"PHRlbXBsYXRlPgogIDxkaXYgc3R5bGU9ImhlaWdodDogMTAwdmg7IHBhZGRpbmctdG9wxxQixDIgIDxjdWItc3RpY2t5IGJvdHRvbT0iNTAiIHBvc2l0aW9uPSLGFscvxzFidXR0b24gdHlwZT0icHJpbWFyeSI+5ZC45bqV6Led56a7IDUwcHg8L8otx2/FEsZwxBI8L2Rpdj4KPC/qAMg="},{default:n(()=>[v]),_:1}),x])}}});export{B as default,R as excerpt,H as frontmatter};
